name: PHP 5.6 and 7.0

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:    
    runs-on: ${{ matrix.operating-system }}
    strategy:      
      matrix:
        operating-system: [ubuntu-16.04,ubuntu-18.04,ubuntu-20.04]
        php-versions: ['5.6','7.0']
        wordpress-versions: ['4.9','5.0','5.1','5.2','5.3','5.4','latest']
    name: PHP ${{ matrix.php-versions }} Test on WordPress ${{ matrix.wordpress-versions }} on ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
            - '3306:3306'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, mysqli
          ini-values: post_max_size=256M, short_open_tag=On
          coverage: xdebug
          tools: phpunit:5.7.27

      - name: Check PHP Version
        run: php -v

      - name: Composer install
        run: composer install --optimize-autoloader --prefer-dist
      
      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wordpress-versions }}
        
      - name: phpunit tests
        run: phpunit
